version: "2.1"

services:
  twitter-merge-lists:
    image: twitter-merge-lists
    container_name: twitter-merge-lists
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9000:8080
