version: "2.1"

services:
  twitter-merge-lists-build:
    image: twitter-merge-lists-build
    container_name: twitter-merge-lists-build
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./docker-build-target:/app/target
      - cargo-cache:/usr/local/cargo/registry

volumes:
  cargo-cache:
