version: "2.1"

services:
  tonarinoyj-update-checker-build:
    image: tonarinoyj-update-checker-build
    container_name: tonarinoyj-update-checker-build
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./docker-build-target:/app/target
      - cargo-cache:/usr/local/cargo/registry
    entrypoint: ["cargo", "build", "--release"]

volumes:
  cargo-cache:
